### ISSUE TITLE
[TRACKING] Create Deployment PR against CNCF TAG repo

### ISSUE THREAD

**Issue by incertum** [falcosecurity/cncf-green-review-testing#4]
Create a PR against https://github.com/cncf-tags/green-reviews-tooling/ to deploy Falco to the CNCF Kubernetes cluster via a Flux watch on our main branch.

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco-cncf-green-review-testing
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: falco-cncf-green-review-testing
  targetNamespace: falco
  timeout: 3m0s
  wait: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: falco-cncf-green-review-testing
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/falcosecurity/cncf-green-review-testing.git

```

Prerequisite is https://github.com/falcosecurity/cncf-green-review-testing/issues/2

Also please note that at first we could limit testing to the `falco-driver-modern-ebpf` as the configs for the other drivers still need to be updated as we approach the Falco 0.37.0 release featuring the new `driver-loader`.

CC @nikimanoledaki
